name: CICD - Workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: liquibase-github-actions/status@v4.29.2
        with:
          changelogFile: example-changelog.sql
          url: ${{ secrets.POSTGRES_URL }}
          password: ${{ secrets.POSTGRES_PASSWORD }}
          username: ${{ secrets.POSTGRES_USERNAME }}
      - uses: liquibase-github-actions/update-sql@v4.29.2
        with:
          changelogFile: example-changelog.sql
          url: ${{ secrets.POSTGRES_URL }}
          password: ${{ secrets.POSTGRES_PASSWORD }}
          username: ${{ secrets.POSTGRES_USERNAME }}
      - uses: liquibase-github-actions/validate@v4.29.2
        with:
          changelogFile: example-changelog.sql
          url: ${{ secrets.POSTGRES_URL }}
          password: ${{ secrets.POSTGRES_PASSWORD }}
          username: ${{ secrets.POSTGRES_USERNAME }}