name: CICD - Workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  JAVA_DISTRIBUTION: 'temurin'
  JAVA_VERSION: '21'
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}