name: CICD - Workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  JAVA_DISTRIBUTION: 'temurin'
  JAVA_VERSION: '21'
  LIQUIBASE_VERSION: '4.29.2'
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Liquibase
        run: |
          wget -O- https://repo.liquibase.com/liquibase.asc | gpg --dearmor > liquibase-keyring.gpg
          cat liquibase-keyring.gpg | sudo tee /usr/share/keyrings/liquibase-keyring.gpg > /dev/null
          echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/liquibase-keyring.gpg] https://repo.liquibase.com stable main' | sudo tee /etc/apt/sources.list.d/liquibase.list
          sudo apt-get update
          sudo apt-get install liquibase=${{ env.LIQUIBASE_VERSION }} -y
      - name: Install Maven Dependencies
        run: mvn clean install
        working-directory: ./infra-sql-liquibase
      - uses: liquibase-github-actions/status@v4.29.2
        with:
          changelogFile: example-changelog.sql
          url: ${{ secrets.POSTGRES_URL }}
          password: ${{ secrets.POSTGRES_PASSWORD }}
          username: ${{ secrets.POSTGRES_USERNAME }}